title: Thomas M. FONTAINE # your name (or website title) here
logo: "/images/1552048013453.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Formateur au Service de Cours d'Adultes de Paris
  <br><br>
  ...
  <br><br>
  <a href="www.linkedin.com/in/thomas-m-fontaine">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
